### ISSUE TITLE
Tip idea: `{{< include _blah.qmd >}}` shortcode

### ISSUE THREAD

**Issue by batpigandme** [mine-cetinkaya-rundel/quarto-tip-a-day#6]
I feel like the question of child documents came up a bunch with R Markdown, so this might be helpful. Good for repeated content, or raw markdown.

Also a nice place to emphatically highlight that the includes *will use* the same rendering engine as the parent `.qmd` (this tripped me up for a little bit).

Example from extant Quarto docs: https://github.com/quarto-dev/quarto-web/blob/c048cac782767f9efba6444188bf710d044d9868/docs/authoring/tables.qmd#L101-L105

**Comment by mine-cetinkaya-rundel** [comment]
Closed with f43225ec43079bfe670f197dc187df8df8054074
